volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             cp -r /app/collected_static/. /backend_static/ &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
  
  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    image: ${DOCKER_USERNAME}/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static:/usr/share/nginx/html
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend