version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - postgres
  
  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    image: ${DOCKER_USERNAME}/kittygram_gateway:latest
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/usr/share/nginx/html/
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend